mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('photos/', include("photo.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/photo/urls.py
from django.urls import path
from . import views

app_name = "photos"

urlpatterns = [
    path("", views.list, name="list"),
    path("create/", views.create, name="create"),
    path("<int:id>/",views.detail, name="detail"),
    path("<int:id>/update/",views.update, name="update"),
    path("<int:id>/delete/",views.delete, name="delete"),
    
]

mysite/photo/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill,ResizeToFit


# Create your models here.
class Photo(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # image = models.ImageField(blank=True)
    image = ProcessedImageField(
            upload_to = "photo/image",
            processors = [ResizeToFit(500,500)],
            format = 'JPEG',
            options= {"quality":90},
            
        )
    
    
    def __str__(self):
        return self.title
    

mysite/photo/views.py
from django.shortcuts import render,redirect
from .models import Photo

# Create your views here.
def list(request):
    photos = Photo.objects.all()
    return render(request,"photo/list.html",{"photos":photos})
    
def create(request):
    if request.method == "POST":
        # POST방식으로 들어왔을때
        title = request.POST.get("title")
        content = request.POST.get("content")
        image = request.FILES.get('image')
        
        Photo.objects.create(title=title,content=content,image=image)
        
        return redirect("photos:list")
        
    else:
        # GET방식으로 들어왔을때
        return render(request,"photo/create.html")

def detail(request,id):
    photo = Photo.objects.get(id=id)
    
    return render(request,"photo/detail.html",{"photo":photo})
    
def update(request,id):
    photo = Photo.objects.get(id=id)
    if request.method == "POST":
        title = request.POST.get("title")
        content = request.POST.get("content")
        
        photo.title = title
        photo.content = content
        photo.save()
        
        return redirect("photos:detail",id)
    else:
        return render(request,"photo/update.html",{"photo":photo})
def delete(request,id):
    photo = Photo.objects.get(id=id)
    photo.delete()
    return redirect("photos:list")
    
    
    
    
    
    
    
    
    

mysite/photo/templates/photo/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'test.css' %}">
    <link rel="shortcut icon" href="{% static 'img/a.jpg' %}">
</head>
<body>
    <ul>
        <!--<li><a href="/photos">홈으로가기</a></li>-->
        <li><a href="{% url 'photos:list' %}">홈으로 가기</a></li>
        <li><a href="{% url 'photos:create' %}">글작성하기</a></li>
    </ul>
    <h3>여기는 파랑색이 되야겠지?</h3>
    {%block bb%}
    {% endblock %}
    
</body>
</html>

mysite/photo/templates/photo/create.html
{% extends "photo/base.html" %}

{% block bb %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" name="title"/>
        <input type="text" name="content"/>
        <input type="file" name="image" accept="image/*" />
        <input type="submit" value="Submit"/>
    </form>
{% endblock %}

mysite/photo/templates/photo/detail.html
{% extends "photo/base.html" %}

{% block bb %}
    <h1>{{photo.title}}</h1>
    <h3>{{photo.content}}</h3>
    {% if photo.image %}
    <img src="{{photo.image.url}}" alt="{{photo.image}}"></img>
    {% endif %}
    <p>{{photo.created_at}}</p>
    <p>{{photo.updated_at}}</p>
    <a href="{% url 'photos:update' photo.id %}">수정하기</a>
    <a href="{% url 'photos:delete' photo.id %}">삭제하기</a>
{% endblock %}

mysite/photo/templates/photo/list.html
{% extends "photo/base.html" %}
{% block bb %}
    <h1>여기는 리스트 페이지입돠</h1>
    <hr>
    {% for photo in photos %}
    <h3>{{photo.title}}</h3>
    <a href="{% url 'photos:detail' photo.id %}">글보기</a>
    {% endfor %}
{% endblock %}

mysite/photo/templates/photo/update.html
{% extends "photo/base.html" %}

{% block bb %}
    <form method="post">
        {% csrf_token %}
        <input type="text" name="title" value="{{photo.title}}"/>
        <input type="text" name="content" value="{{photo.content}}"/>
        <input type="submit" value="Submit"/>
    </form>
{% endblock %}